apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: mediuscare
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: alihassan065/mediuscare-backend:v1
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/mediuscare"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: mediuscare
spec:
  selector:
    app: backend
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30500
